"database":
  "config": "mongodb://localhost:27017/"
  "db": "lovelife"
"global":
  "captcha":
"session":
    "session_secret":"3cdcb1f00803b6e78ab50b466a40b9977db396840c28307f428b25e2277f1bcc",
    "session_timeout":60,
    "store_options":{
            "redis_host": "localhost",
                "redis_port": 6379,
                "redis_pass": ""
        }
